// The in-game manual: every entry in English and Spanish, grouped by
// category. The manual screen adds search, A-Z / Z-A sorting, category
// filters and collapsible entries.
export const MANUAL_CATS = {
  basics: { en: 'Basics', es: 'Lo básico' },
  survival: { en: 'Survival', es: 'Supervivencia' },
  combat: { en: 'Combat', es: 'Combate' },
  squad: { en: 'Squad & orders', es: 'Escuadra y órdenes' },
  forts: { en: 'Forts', es: 'Fuertes' },
  enemy: { en: 'The enemy', es: 'El enemigo' },
  missions: { en: 'Missions', es: 'Misiones' },
  game: { en: 'Game & settings', es: 'Partida y ajustes' },
};

const E = (id, cat, enT, en, esT, es) => ({ id, cat, en: { title: enT, text: en }, es: { title: esT, text: es } });

export const MANUAL = [
  // ---------------------------------------------------------------- basics
  E('move', 'basics', 'Moving around',
    'WASD to walk, Shift to run, C to crouch (quieter and harder to spot), Space to jump. Hold Space in water to swim up. Logs and ladders can be climbed by walking into them.',
    'Moverse', 'WASD para caminar, Mayús para correr, C para agacharse (más silencioso y difícil de ver), Espacio para saltar. Mantén Espacio en el agua para subir nadando. Los troncos y escaleras se trepan caminando hacia ellos.'),
  E('dig', 'basics', 'Digging and building',
    'Left click digs the block you aim at; harder blocks take longer. Right click places the selected block. Built-in fort walls and the cabin cannot be dug.',
    'Cavar y construir', 'El clic izquierdo cava el bloque al que apuntas; los bloques duros tardan más. El clic derecho coloca el bloque elegido. Los muros de los fuertes y la cabaña no se pueden cavar.'),
  E('hotbar', 'basics', 'Hotbar and inventory',
    'Keys 1-9 or the mouse wheel pick an item. I (or Tab) opens the inventory, where you can arrange the hotbar.',
    'Barra rápida e inventario', 'Las teclas 1-9 o la rueda del ratón eligen un objeto. I (o Tab) abre el inventario, donde puedes ordenar la barra.'),
  E('water', 'basics', 'Water, rafts and bridges',
    'You can swim, but not for ever: watch the breath bar under water. Craft a raft to cross lakes; place it on open water and click it to board. Blocks placed from the water build a bridge.',
    'Agua, balsas y puentes', 'Puedes nadar, pero no eternamente: vigila la barra de aire bajo el agua. Fabrica una balsa para cruzar lagos; colócala en agua abierta y haz clic para subir. Los bloques colocados desde el agua forman un puente.'),
  E('dark', 'basics', 'Tunnels and darkness',
    'Tunnels, trenches and holes get darker the deeper you go and the farther from the opening, even at midday. It never gets pitch black, and the flashlight (F) always works.',
    'Túneles y oscuridad', 'Los túneles, trincheras y agujeros se oscurecen cuanto más profundo y lejos de la entrada, incluso a mediodía. Nunca está totalmente negro y la linterna (F) siempre funciona.'),
  E('flashlight', 'basics', 'Flashlight',
    'F turns the flashlight on and off. It lights tunnels and the night, but enemies can see you much farther away while it is on.',
    'Linterna', 'F enciende y apaga la linterna. Ilumina túneles y la noche, pero el enemigo te ve desde mucho más lejos mientras está encendida.'),
  E('radar', 'basics', 'Radar (minimap)',
    'The round radar in the corner turns with you. Red dots are enemies, blue dots allies; your squad is coloured by their current order. Squares are forts in their owner\'s colour. Order targets (advance points, holds, forts to attack or defend) are marked, pinned to the rim when far away. Units only show within range.',
    'Radar (minimapa)', 'El radar redondo de la esquina gira contigo. Los puntos rojos son enemigos y los azules aliados; tu escuadra se colorea según su orden. Los cuadrados son fuertes del color de su dueño. Los objetivos de las órdenes (puntos de avance, posiciones, fuertes a atacar o defender) aparecen marcados, en el borde si están lejos. Solo se ven las unidades cercanas.'),
  // -------------------------------------------------------------- survival
  E('hunger', 'survival', 'Hunger and food',
    'Hunger slowly drops. Hunt animals, cook the meat on a campfire and eat it (right click with food). Starving makes you sick and, in the end, kills you. Your own forts feed you while you are inside, and their ration crates (E) give food.',
    'Hambre y comida', 'El hambre baja poco a poco. Caza animales, cocina la carne en una hoguera y cómela (clic derecho con la comida). Pasar hambre te enferma y al final te mata. Tus fuertes te alimentan mientras estás dentro y sus cajas de raciones (E) dan comida.'),
  E('hunting', 'survival', 'Hunting',
    'Animals hear you running and flee. Crouch and approach slowly from behind. A knife kills quietly; guns are loud and scare everything nearby.',
    'Caza', 'Los animales te oyen correr y huyen. Agáchate y acércate despacio por detrás. El cuchillo mata en silencio; las armas de fuego hacen ruido y espantan a todo lo cercano.'),
  E('campfire', 'survival', 'Campfires and crafting',
    'Light a campfire with flint and steel. E near a campfire opens crafting: weapons, ammunition, TNT, grenades, rafts and more. K opens simple crafting anywhere.',
    'Hogueras y fabricación', 'Enciende una hoguera con pedernal y eslabón. E junto a una hoguera abre la fabricación: armas, munición, TNT, granadas, balsas y más. K abre la fabricación sencilla en cualquier sitio.'),
  E('health', 'survival', 'Health and medkits',
    'Health comes back slowly while you are well fed. Medkits heal at once. Falls from high up hurt.',
    'Salud y botiquines', 'La salud vuelve poco a poco si estás bien alimentado. Los botiquines curan al instante. Las caídas desde lo alto hacen daño.'),
  // ---------------------------------------------------------------- combat
  E('weapons', 'combat', 'Weapons',
    'Knife (silent, deadly from behind), pistol, bolt-action rifle, submachine gun and sniper rifle. Guns need iron to craft. Crouching and standing still make you more accurate.',
    'Armas', 'Cuchillo (silencioso, letal por la espalda), pistola, fusil de cerrojo, subfusil y fusil de francotirador. Las armas se fabrican con hierro. Agacharse y estar quieto mejora la puntería.'),
  E('scope', 'combat', 'Scope and binoculars',
    'Z (or right click with the sniper rifle) brings the scope up: a circular view with a fine reticle and a blurred dark surround, zooming smoothly. Without the sniper rifle, Z uses binoculars. Your aim sways with your breathing; hold Shift to steady it for a few seconds. Z again lowers it. Ordinary guns keep the normal crosshair and the knife a dot.',
    'Mira y prismáticos', 'Z (o clic derecho con el fusil de francotirador) sube la mira: una vista circular con retícula fina y el borde oscuro y borroso, con zoom suave. Sin el fusil de francotirador, Z usa los prismáticos. La puntería se mueve con la respiración; mantén Mayús para estabilizarla unos segundos. Z de nuevo la baja. Las demás armas usan la mira normal y el cuchillo un punto.'),
  E('grenades', 'combat', 'Grenades and smoke',
    'Left click throws. Grenades explode after a short fuse; smoke grenades hide you from enemy eyes.',
    'Granadas y humo', 'El clic izquierdo lanza. Las granadas explotan tras una mecha corta; las de humo te ocultan de los ojos enemigos.'),
  E('tnt', 'combat', 'TNT',
    'Place TNT and light it with flint and steel, or shoot it. It blows craters but spares fort walls; three charges (or twelve grenades) bring a fort door down. Walk into enemy TNT to pull its wires.',
    'TNT', 'Coloca TNT y enciéndelo con pedernal y eslabón, o dispárale. Abre cráteres pero respeta los muros de los fuertes; tres cargas (o doce granadas) derriban la puerta de un fuerte. Acércate al TNT enemigo para arrancarle los cables.'),
  E('tank', 'combat', 'The tank',
    'A rare enemy tank roams the land. Bullets barely scratch it; use grenades and TNT. Its commander bails out when it burns.',
    'El tanque', 'Un raro tanque enemigo recorre el terreno. Las balas apenas lo arañan; usa granadas y TNT. Su comandante salta fuera cuando arde.'),
  // ----------------------------------------------------------------- squad
  E('squad', 'squad', 'Your squad',
    'In Play with Allies you lead a squad of any size, from a few soldiers to everyone. Taking too many soldiers away leaves your forts weakly guarded. The squad list under the radar shows each soldier, his order and his health.',
    'Tu escuadra', 'En Jugar con aliados diriges una escuadra de cualquier tamaño, desde unos pocos soldados hasta todos. Llevarte a demasiados deja tus fuertes mal defendidos. La lista bajo el radar muestra a cada soldado, su orden y su salud.'),
  E('wheel', 'squad', 'The order wheel',
    'Q opens the order wheel. Move the mouse toward an order and click, or press its number. On phones, use the contextual Follow me and Orders buttons instead. Orders: Follow me, Hold position, Defend the base, Take cover, Spread out, Advance here, Attack this fort, and the squad formation.',
    'La rueda de órdenes', 'Q abre la rueda de órdenes. Mueve el ratón hacia una orden y haz clic, o pulsa su número. En el móvil se usan los botones contextuales Sígueme y Órdenes. Órdenes: Seguidme, Mantened la posición, Defended la base, A cubierto, Dispersaos, Avanzad aquí, Atacad este fuerte y la formación.'),
  E('targeting', 'squad', 'Aiming orders',
    'Orders use what you look at when you open the wheel: Advance goes to that spot, Attack goes for that fort (or the nearest enemy fort), Defend goes to that allied fort (or the nearest one).',
    'Órdenes con puntería', 'Las órdenes usan lo que miras al abrir la rueda: Avanzad va a ese punto, Atacad va a ese fuerte (o al fuerte enemigo más cercano), Defended va a ese fuerte aliado (o al más cercano).'),
  E('recipients', 'squad', 'Who gets the order',
    'G adds the soldier you aim at to a selected group (G again removes him; G at nothing clears the group). Orders go to the selected group; with no group, to the soldier you aim at; otherwise to the whole squad. "Follow me" to the whole squad also gathers allies nearby who are not guarding a fort. Aim at a soldier and press 9 in the wheel to talk to him (ask for iron or his gear).',
    'Quién recibe la orden', 'G añade al soldado al que apuntas a un grupo elegido (G otra vez lo quita; G sin apuntar a nadie borra el grupo). Las órdenes van al grupo elegido; sin grupo, al soldado al que apuntas; si no, a toda la escuadra. "Seguidme" a toda la escuadra también reúne a los aliados cercanos que no guardan un fuerte. Apunta a un soldado y pulsa 9 en la rueda para hablar con él (pedirle hierro o su equipo).'),
  E('orders', 'squad', 'What each order does',
    'Follow me: they move with you in formation. Hold position: they stay put, even if you leave. Defend the base: they go to the fort and patrol it. Take cover: each finds cover nearby and stays down. Spread out: wider spacing (again to close up). Advance here: they move to the spot and hold it. Attack this fort: they blow the door and storm it, then defend it. Every soldier answers on the radio and his marker changes.',
    'Qué hace cada orden', 'Seguidme: te acompañan en formación. Mantened la posición: se quedan, aunque te vayas. Defended la base: van al fuerte y patrullan. A cubierto: cada uno busca cobertura cerca y se agacha. Dispersaos: más separación (otra vez para juntarse). Avanzad aquí: van al punto y lo mantienen. Atacad este fuerte: vuelan la puerta, lo asaltan y luego lo defienden. Cada soldado responde por radio y cambia su marcador.'),
  E('formation', 'squad', 'Formations',
    'Loose (default), Line or Column, chosen in the wheel or in Settings. Your squad keeps 8-15 m behind and to the sides, never in your line of fire or blocking your view, and goes single file in narrow places such as trenches and forts. Nobody stands in a doorway.',
    'Formaciones', 'Abierta (por defecto), En línea o En columna, desde la rueda o en Ajustes. La escuadra va 8-15 m por detrás y a los lados, nunca en tu línea de tiro ni tapando la vista, y en fila india en sitios estrechos como trincheras y fuertes. Nadie se queda en una puerta.'),
  E('underfire', 'squad', 'Under fire',
    'When shooting starts your soldiers scatter to cover, crouch, pop up to return fire and keep their distance from each other. When it has been quiet for a while they regroup in formation.',
    'Bajo fuego', 'Cuando empiezan los disparos tus soldados buscan cobertura, se agachan, asoman para responder y se mantienen separados. Cuando todo lleva un rato en calma vuelven a la formación.'),
  E('fallen', 'squad', 'Fallen allies',
    'Defeated allies come back some time later near one of your forts and walk back to it. They are no longer part of your squad; recruit them again with "Follow me".',
    'Aliados caídos', 'Los aliados abatidos vuelven al rato cerca de uno de tus fuertes y caminan hasta él. Ya no forman parte de tu escuadra; vuelve a reclutarlos con "Seguidme".'),
  // ----------------------------------------------------------------- forts
  E('forts', 'forts', 'Forts',
    'Forts are always lit inside. Their doors open only for their owners. A fort is captured when its defenders are gone or surrender (officer down, or door blown and outnumbered) and you or your allies are inside. Your forts feed you and sound a siren when attacked.',
    'Fuertes', 'Los fuertes siempre están iluminados por dentro. Sus puertas solo se abren para sus dueños. Se captura un fuerte cuando sus defensores caen o se rinden (oficial abatido, o puerta volada y en inferioridad) y tú o tus aliados estáis dentro. Tus fuertes te alimentan y hacen sonar una sirena si los atacan.'),
  E('guards', 'forts', 'Garrisons',
    'Every fort keeps guards that never leave it. The rest of its soldiers may be sent out in attack squads.',
    'Guarniciones', 'Cada fuerte tiene guardias que nunca salen. El resto de sus soldados puede salir en escuadras de ataque.'),
  // ----------------------------------------------------------------- enemy
  E('raids', 'enemy', 'Attack squads',
    'The enemy sends squads of about 5-6 soldiers from its forts to attack yours. There is no warning when they leave; you only see them on the radar once they are close. Difficulty sets how big and how frequent the squads are. Attacks are lighter by day and heavier at night.',
    'Escuadras de ataque', 'El enemigo envía escuadras de unos 5-6 soldados desde sus fuertes contra los tuyos. No hay aviso cuando salen; solo los ves en el radar cuando están cerca. La dificultad decide su tamaño y frecuencia. Los ataques son más ligeros de día y más fuertes de noche.'),
  E('patrols', 'enemy', 'Patrols',
    'Both sides keep patrols of about 4-6 soldiers out in the field at all times. Each patrol leaves a fort with a purpose: it walks toward a nearby fort, a river crossing, or the area around the other side\'s fort or your cabin, then returns home. Some guards always stay in every fort. Difficulty sets how many patrols there are and how big they are; in Day only worlds they are as active as at night. There is no warning when they leave: you meet them in the field or see them on the radar.',
    'Patrullas', 'Los dos bandos mantienen siempre patrullas de unos 4-6 soldados en el terreno. Cada patrulla sale de un fuerte con un propósito: va hacia un fuerte cercano, un paso del río o los alrededores de un fuerte del otro bando o de tu cabaña, y luego vuelve a casa. En cada fuerte siempre quedan guardias. La dificultad decide cuántas patrullas hay y su tamaño; en los mundos de Solo de día están igual de activas que de noche. No hay aviso cuando salen: te las encuentras en el terreno o las ves en el radar.'),
  E('fortpaths', 'forts', 'How soldiers move in forts',
    'Soldiers only enter and leave a fort through its door, walking around the walls to reach it and waiting their turn if the doorway is busy. Guards reach the rampart by the ladders and climb down the same way, for example when you tell them to follow you.',
    'Cómo se mueven los soldados en los fuertes', 'Los soldados solo entran y salen de un fuerte por la puerta: rodean los muros para llegar a ella y esperan su turno si el paso está ocupado. Los guardias suben a la muralla por las escaleras de mano y bajan por ellas, por ejemplo cuando les ordenas que te sigan.'),
  E('tactics', 'enemy', 'Enemy tactics',
    'In the field enemies spread out, take cover behind trees, walls and terrain, and shoot from there. Sappers set charges at fort doors. Flank them: cover only works from one side.',
    'Tácticas enemigas', 'En campo abierto el enemigo se dispersa, se cubre tras árboles, muros y el terreno y dispara desde ahí. Los zapadores ponen cargas en las puertas. Flanquéalos: la cobertura solo protege por un lado.'),
  E('cabin', 'enemy', 'The cabin (Play Alone)',
    'Playing alone, enemy squads attack the forts you captured and also come for your cabin: they surround it and wait for you to come out.',
    'La cabaña (Jugar solo)', 'Jugando solo, las escuadras enemigas atacan los fuertes que capturaste y también van a tu cabaña: la rodean y esperan a que salgas.'),
  E('respawn', 'enemy', 'Defeated enemies',
    'Defeated enemies come back near one of their forts, walk back to it and attack again later, so their numbers stay the same. If they have no forts left, survivors scatter, regroup, craft weapons and counterattack.',
    'Enemigos abatidos', 'Los enemigos abatidos vuelven cerca de uno de sus fuertes, caminan hasta él y atacan otra vez más tarde, así que su número no cambia. Si no les quedan fuertes, los supervivientes se dispersan, se reagrupan, fabrican armas y contraatacan.'),
  // ------------------------------------------------------------------ game
  E('modes', 'game', 'Modes',
    'War: survive, build, hunt and fight, alone (start in a cabin) or with allies. Peace: unlimited materials, flying (double-tap Space), always daytime and no enemies.',
    'Modos', 'Guerra: sobrevive, construye, caza y lucha, solo (empiezas en una cabaña) o con aliados. Paz: materiales ilimitados, vuelo (doble toque de Espacio), siempre de día y sin enemigos.'),
  E('timeofday', 'game', 'Time of day',
    'When you start a War game you choose "Day and night" (a full cycle: lighter enemy attacks by day, heavier at night) or "Day only" (always daylight, but the enemy attacks constantly at night-time strength). The choice is saved with the world. Peace mode is always daytime.',
    'Hora del día', 'Al empezar una partida de Guerra eliges "Día y noche" (ciclo completo: ataques más ligeros de día y más fuertes de noche) o "Solo de día" (siempre hay luz, pero el enemigo ataca sin parar con la fuerza de la noche). La elección se guarda con el mundo. El modo Paz siempre es de día.'),
  E('difficulty', 'game', 'Difficulty',
    'From Beginner to Impossible: more and bigger enemy squads, scarcer food and forts farther apart.',
    'Dificultad', 'De Principiante a Imposible: más escuadras enemigas y más grandes, menos comida y fuertes más alejados.'),
  E('quality', 'game', 'Graphics quality',
    'Low, Medium or High. Higher quality draws smoother soldiers, fully animates more of them at once and shows their kit and faces from farther away. Lower quality runs better on slower devices.',
    'Calidad gráfica', 'Baja, Media o Alta. Más calidad dibuja soldados más suaves, anima por completo a más a la vez y muestra su equipo y cara desde más lejos. Menos calidad va mejor en equipos lentos.'),
  E('saving', 'game', 'Saving',
    'The world saves itself every minute and when you quit to the menu. Several worlds can be kept; load or delete them from Load Game.',
    'Guardar', 'El mundo se guarda solo cada minuto y al salir al menú. Puedes tener varios mundos; cárgalos o bórralos desde Cargar partida.'),
  E('language', 'game', 'Language',
    'English or Spanish, from the main menu or Settings.',
    'Idioma', 'Inglés o español, desde el menú principal o los Ajustes.'),

  // ------------------------------------------------------------- additions
  E('controls', 'basics', 'Controls',
    'Keyboard and mouse: WASD move, Shift run, C crouch, Space jump/swim, left click dig/attack, right click place/use, 1-9 hotbar, E campfire/rations/chest, Q order wheel, G select soldier, T follow me, Y ask for iron, U ask for a weapon, F flashlight, Z scope/binoculars, M war map, I inventory, K craft, Esc pause. Phones: left thumb moves, right side looks; buttons for jump, use, action, run, crouch, zoom, light, bag, craft and map. Squad buttons appear only when they make sense.',
    'Controles', 'Teclado y ratón: WASD moverse, Mayús correr, C agacharse, Espacio saltar/nadar, clic izquierdo cavar/atacar, clic derecho colocar/usar, 1-9 barra, E hoguera/raciones/baúl, Q rueda de órdenes, G elegir soldado, T sígueme, Y pedir hierro, U pedir un arma, F linterna, Z mira/prismáticos, M mapa de guerra, I inventario, K fabricar, Esc pausa. Móvil: el pulgar izquierdo mueve y el lado derecho mira; hay botones para saltar, usar, acción, correr, agacharse, zoom, luz, bolsa, fabricar y mapa. Los botones de escuadra solo aparecen cuando tienen sentido.'),
  E('blocks', 'basics', 'Blocks',
    'Dirt, mud, rubble, logs, planks, leaves, stone, iron ore, sandbags, barbed wire and TNT. Sandbags and wire make good cover and obstacles; wire slows everyone and cuts enemies. Iron ore is used to craft guns.',
    'Bloques', 'Tierra, barro, escombros, troncos, tablones, hojas, piedra, mineral de hierro, sacos terreros, alambre de espino y TNT. Los sacos y el alambre son buena cobertura y obstáculo; el alambre frena a todos y hiere al enemigo. El hierro sirve para fabricar armas.'),
  E('nearforts', 'forts', 'Building near forts',
    'Built-in forts cannot be damaged or changed. Outside a fort you can dig and build anywhere, right up against its walls and in front of its door: trenches, sandbags, cover, and TNT at the door. Inside a fort the only thing you can place is a campfire, for crafting.',
    'Construir junto a los fuertes', 'Los fuertes no se pueden dañar ni modificar. Fuera de un fuerte puedes cavar y construir donde quieras, pegado a sus muros y delante de la puerta: trincheras, sacos terreros, cobertura y TNT en la puerta. Dentro de un fuerte solo puedes colocar una hoguera para fabricar.'),
  E('swimming', 'basics', 'Swimming and crossing water',
    'Swimming is slow and you can only use a pistol or a knife in the water. Soldiers follow the same rules: they prefer bridges and shallow fords, and swim only when they must, so they are exposed while crossing.',
    'Nadar y cruzar el agua', 'Nadar es lento y en el agua solo puedes usar pistola o cuchillo. Los soldados siguen las mismas reglas: prefieren puentes y vados poco profundos y solo nadan cuando no queda otra, así que están expuestos al cruzar.'),
  E('trapped', 'enemy', 'Soldiers stuck in holes',
    'A soldier who falls into a hole first tries to climb out or walk around it. If he is still stuck after about 10 seconds he counts as defeated and comes back near one of his side\'s forts.',
    'Soldados atrapados en agujeros', 'Un soldado que cae en un agujero intenta trepar o rodearlo. Si a los 10 segundos sigue atrapado cuenta como abatido y vuelve cerca de uno de los fuertes de su bando.'),
  E('squadphone', 'squad', 'Squad commands on phones',
    'There are no permanent squad buttons. Stand beside an allied soldier and a "Follow me" button appears: it recruits him and the allies close to you, and also calls back soldiers who are holding or guarding. While you have a squad, a small Orders button opens a short menu: Hold position, Defend the base, Spread out, Take cover, Attack this fort. "Ask for iron" and "Ask for a weapon" appear beside a soldier.',
    'Órdenes de escuadra en el móvil', 'No hay botones de escuadra fijos. Ponte junto a un soldado aliado y aparece "Sígueme": lo recluta a él y a los aliados cercanos, y también llama a los que mantienen posición o hacen guardia. Mientras tengas escuadra, un pequeño botón Órdenes abre un menú corto: Mantened la posición, Defended la base, Dispersaos, A cubierto, Atacad este fuerte. "Pedir hierro" y "Pedir un arma" aparecen junto a un soldado.'),
  E('cabinfull', 'survival', 'The cabin',
    'Playing alone you start in a log cabin that cannot be destroyed and that enemies cannot enter. It has an ever-burning campfire for crafting, a bed and a storage chest. Iron is very plentiful around it. If you are defeated you wake up at the bed with only what you left in the chest. Starving (about 5 in-game days without food) ends the game.',
    'La cabaña', 'Jugando solo empiezas en una cabaña de troncos indestructible en la que el enemigo no puede entrar. Tiene una hoguera que nunca se apaga para fabricar, una cama y un baúl. Alrededor hay muchísimo hierro. Si caes, despiertas junto a la cama solo con lo que dejaste en el baúl. Morir de hambre (unos 5 días sin comer) termina la partida.'),
  E('warmap', 'basics', 'War map',
    'M (or MAP on phones, or the pause menu) opens the war map: every fort in its owner\'s colour (allied, enemy, unclaimed), your position, the cabin when playing alone and the current mission objective.',
    'Mapa de guerra', 'M (o MAPA en el móvil, o el menú de pausa) abre el mapa de guerra: todos los fuertes con el color de su dueño (aliado, enemigo, sin dueño), tu posición, la cabaña si juegas solo y el objetivo de la misión.'),
  E('music', 'game', 'Music',
    'A calm march plays on the main menu and stops during play. Change its volume or mute it in Settings, or tap the speaker icon on the main menu. Your choice is remembered.',
    'Música', 'En el menú principal suena una marcha tranquila que se detiene al jugar. Cambia su volumen o silénciala en Ajustes, o toca el icono del altavoz del menú principal. Se recuerda tu elección.'),
  E('settings', 'game', 'Settings',
    'Language, graphics quality, render distance, sound volume, music volume and mute, mouse sensitivity and invert, blood on/off, minimap on/off and size, squad formation and touch button size.',
    'Ajustes', 'Idioma, calidad gráfica, distancia de dibujado, volumen del sonido, volumen y silencio de la música, sensibilidad e inversión del ratón, sangre sí/no, minimapa sí/no y tamaño, formación de la escuadra y tamaño de los botones táctiles.'),
  E('statsm', 'game', 'Statistics',
    'Days survived, forts captured and lost, enemies defeated, animals hunted, longest survival alone, missions completed and medals, with War statistics per difficulty. They can be reset from the Statistics screen.',
    'Estadísticas', 'Días sobrevividos, fuertes capturados y perdidos, enemigos abatidos, animales cazados, supervivencia más larga en solitario, misiones cumplidas y medallas, con las de guerra por dificultad. Se pueden reiniciar desde la pantalla de Estadísticas.'),
  E('slots', 'game', 'Save slots',
    'Each saved world remembers its mode, game type, difficulty, time of day and mission progress. Delete one world or all of them from Load Game. Worlds from older versions are marked outdated and rebuilt when loaded.',
    'Partidas guardadas', 'Cada mundo guardado recuerda su modo, tipo de partida, dificultad, hora del día y el progreso de la misión. Borra un mundo o todos desde Cargar partida. Los mundos de versiones antiguas aparecen como antiguos y se reconstruyen al cargarlos.'),
  E('app', 'game', 'Install and play offline',
    'The game can be installed as an app from your browser menu and then plays offline. When a new version is ready, a notice offers to reload.',
    'Instalar y jugar sin conexión', 'El juego se puede instalar como aplicación desde el menú del navegador y después funciona sin conexión. Cuando hay una versión nueva, un aviso te ofrece recargar.'),
  E('credits', 'game', 'Credits',
    'Mighty Man o\' War. Original game, textures, sounds, music arrangement and logo made for this game. Menu music arranged from the public-domain 1860s tune "When Johnny Comes Marching Home". 3D engine: three.js.',
    'Créditos', 'Mighty Man o\' War. Juego, texturas, sonidos, arreglo musical y logotipo originales, hechos para este juego. La música del menú es un arreglo de la melodía de dominio público de la década de 1860 "When Johnny Comes Marching Home". Motor 3D: three.js.'),
  E('opmis', 'missions', 'Open World or Missions',
    'Open World is the free, endless game: no assigned missions, you set your own goals. Missions set up the world for one task; pick one from the list and replay it as often as you like. After a mission you can replay it, pick another or carry on in Open World.',
    'Mundo abierto o misiones', 'El mundo abierto es la partida libre y sin fin: sin misiones asignadas, tú pones tus metas. En las misiones el mundo se prepara para una tarea; elige una de la lista y repítela cuando quieras. Al terminar puedes repetirla, elegir otra o seguir en mundo abierto.'),
  E('medals', 'missions', 'Medals',
    'Completing a mission gives a bronze, silver or gold medal depending on how well you did (time left, health, carriers saved and so on). Your best medal shows on the mission list.',
    'Medallas', 'Cumplir una misión da una medalla de bronce, plata u oro según lo bien que lo hayas hecho (tiempo restante, salud, porteadores salvados…). Tu mejor medalla aparece en la lista de misiones.'),
  E('wmissions', 'missions', 'War missions',
    'Take the Fort, Trench Defense, Hold the Fort, Scout the Enemy, Tree Sniper, Bridge Defense, Supply Run, Demolition and Capture Every Fort (hardest difficulties only). Playing alone you get the missions that make sense solo (with smaller versions of Take the Fort and Capture Every Fort); Bridge Defense and Supply Run need allies. Difficulty sets enemy numbers, squad size, time limits and supplies.',
    'Misiones de guerra', 'Tomar el fuerte, Defensa de trinchera, Resistir en el fuerte, Reconocimiento, Francotirador en el árbol, Defensa del puente, Convoy de suministros, Demolición y Capturar todos los fuertes (solo en las dificultades más duras). Jugando solo tienes las misiones que tienen sentido en solitario (con versiones reducidas de Tomar el fuerte y Capturar todos los fuertes); Defensa del puente y Convoy necesitan aliados. La dificultad decide el número de enemigos, el tamaño de las escuadras, los límites de tiempo y los suministros.'),
  E('pmissions', 'missions', 'Peace missions',
    'Build a Shack (walls, roof and a door, at least 3×3 inside), Hunter\'s Supply (six animals), Explorer (35% of the map, with a percentage tracker) and Bridge Builder (cross six blocks of water on your own bridge). No enemies and no time pressure.',
    'Misiones de paz', 'Construir una cabaña (paredes, techo y puerta, al menos 3×3 por dentro), Provisiones del cazador (seis animales), Explorador (el 35 % del mapa, con contador) y Constructor de puentes (cruza seis bloques de agua por tu propio puente). Sin enemigos y sin prisas.'),
  E('m_take', 'missions', 'Take the Fort', 'Take the Fort: build a squad and capture the marked enemy fort before time runs out.', 'Tomar el fuerte', 'Tomar el fuerte: forma una escuadra y captura el fuerte enemigo marcado antes de que se acabe el tiempo.'),
  E('m_trench', 'missions', 'Trench Defense', 'Trench Defense: you get time to dig in with your shovel, sandbags and wire, then waves of enemy squads attack until the timer ends.', 'Defensa de trinchera', 'Defensa de trinchera: tienes tiempo para atrincherarte con la pala, sacos y alambre; después atacan oleadas de escuadras hasta que acaba el tiempo.'),
  E('m_hold', 'missions', 'Hold the Fort', 'Hold the Fort: a surprisingly large force tries to blow your door with TNT. Shoot the charges or walk up to them to pull the wires. You lose if the fort is taken.', 'Resistir en el fuerte', 'Resistir en el fuerte: una fuerza sorprendentemente grande intenta volar tu puerta con TNT. Dispara a las cargas o acércate para arrancarles los cables. Pierdes si toman el fuerte.'),
  E('m_scout', 'missions', 'Scout the Enemy', 'Scout the Enemy: watch the marked fort through the binoculars (Z) to count its soldiers, find the officer with the binoculars, then get back to where you started.', 'Reconocimiento', 'Reconocimiento: observa el fuerte marcado con los prismáticos (Z) para contar sus soldados, localiza al oficial con los prismáticos y vuelve al punto de partida.'),
  E('m_sniper', 'missions', 'Tree Sniper', 'Tree Sniper: climb the tree beside you and take out the enemy officer before his squad moves out.', 'Francotirador en el árbol', 'Francotirador en el árbol: sube al árbol de al lado y abate al oficial enemigo antes de que su escuadra se ponga en marcha.'),
  E('m_bridge', 'missions', 'Bridge Defense', 'Bridge Defense: hold your end of a bridge with your squad. If three enemies reach your bank, the mission fails.', 'Defensa del puente', 'Defensa del puente: defiende tu extremo del puente con tu escuadra. Si tres enemigos llegan a tu orilla, la misión fracasa.'),
  E('m_supply', 'missions', 'Supply Run', 'Supply Run: escort three supply carriers to your fort across enemy ground; ambushes are waiting.', 'Convoy de suministros', 'Convoy de suministros: escolta a tres porteadores hasta tu fuerte por terreno enemigo; habrá emboscadas.'),
  E('m_demo', 'missions', 'Demolition', "Demolition: blow open the marked fort's door with TNT (3 charges) or grenades (12) before the timer ends.", 'Demolición', 'Demolición: vuela la puerta del fuerte marcado con TNT (3 cargas) o granadas (12) antes de que acabe el tiempo.'),
  E('m_all', 'missions', 'Capture Every Fort', 'Capture Every Fort: take every enemy fort. A long, very hard mission for Hard and Impossible.', 'Capturar todos los fuertes', 'Capturar todos los fuertes: toma todos los fuertes enemigos. Una misión larga y muy dura, para Difícil e Imposible.'),
];
