// The in-game manual: every entry in English and Spanish, grouped by
// category. The manual screen adds search, A-Z / Z-A sorting, category
// filters and collapsible entries.
export const MANUAL_CATS = {
  basics: { en: 'Basics', es: 'Lo básico' },
  survival: { en: 'Survival', es: 'Supervivencia' },
  combat: { en: 'Combat', es: 'Combate' },
  squad: { en: 'Squad & orders', es: 'Escuadra y órdenes' },
  forts: { en: 'Forts', es: 'Fuertes' },
  enemy: { en: 'The enemy', es: 'El enemigo' },
  missions: { en: 'Missions', es: 'Misiones' },
  town: { en: 'Town Life', es: 'Town Life' },
  game: { en: 'Game & settings', es: 'Partida y ajustes' },
};

const E = (id, cat, enT, en, esT, es) => ({ id, cat, en: { title: enT, text: en }, es: { title: esT, text: es } });

export const MANUAL = [
  // ---------------------------------------------------------------- basics
  E('move', 'basics', 'Moving around',
    'WASD to walk, Shift to run, C to crouch (quieter and harder to spot), Space to jump. Hold Space in water to swim up. Logs and ladders can be climbed by walking into them.',
    'Moverse', 'WASD para caminar, Mayús para correr, C para agacharse (más silencioso y difícil de ver), Espacio para saltar. Mantén Espacio en el agua para subir nadando. Los troncos y escaleras se trepan caminando hacia ellos.'),
  E('dig', 'basics', 'Digging and building',
    'Left click digs the block you aim at; harder blocks take longer. Right click places the selected block. Built-in fort walls and the cabin cannot be dug.',
    'Cavar y construir', 'El clic izquierdo cava el bloque al que apuntas; los bloques duros tardan más. El clic derecho coloca el bloque elegido. Los muros de los fuertes y la cabaña no se pueden cavar.'),
  E('hotbar', 'basics', 'Hotbar and inventory',
    'Keys 1-9 or the mouse wheel pick an item. I (or Tab) opens the inventory, where you can arrange the hotbar.',
    'Barra rápida e inventario', 'Las teclas 1-9 o la rueda del ratón eligen un objeto. I (o Tab) abre el inventario, donde puedes ordenar la barra.'),
  E('water', 'basics', 'Water, rafts and bridges',
    'You can swim, but not for ever: watch the air bar under water (see Diving and air). Craft a raft to cross lakes; place it on open water and right-click it to board. Blocks placed from the water build a bridge.',
    'Agua, balsas y puentes', 'Puedes nadar, pero no eternamente: vigila la barra de aire bajo el agua (mira Buceo y aire). Fabrica una balsa para cruzar lagos; colócala en agua abierta y haz clic derecho sobre ella para subir. Los bloques colocados desde el agua forman un puente.'),
  E('dark', 'basics', 'Tunnels and darkness',
    'Tunnels, trenches and holes get darker the deeper you go and the farther from the opening, even at midday. It never gets pitch black, and the flashlight (F) always works.',
    'Túneles y oscuridad', 'Los túneles, trincheras y agujeros se oscurecen cuanto más profundo y lejos de la entrada, incluso a mediodía. Nunca está totalmente negro y la linterna (F) siempre funciona.'),
  E('flashlight', 'basics', 'Flashlight',
    'F turns the flashlight on and off. It lights tunnels and the night, but enemies can see you much farther away while it is on.',
    'Linterna', 'F enciende y apaga la linterna. Ilumina túneles y la noche, pero el enemigo te ve desde mucho más lejos mientras está encendida.'),
  E('radar', 'basics', 'Radar (minimap)',
    'The round radar in the corner turns with you. Red dots are enemies, blue dots allies; your squad is coloured by their current order. Squares are forts in their owner\'s colour. Order targets (advance points, holds, forts to attack or defend) are marked, pinned to the rim when far away. Units only show within range.',
    'Radar (minimapa)', 'El radar redondo de la esquina gira contigo. Los puntos rojos son enemigos y los azules aliados; tu escuadra se colorea según su orden. Los cuadrados son fuertes del color de su dueño. Los objetivos de las órdenes (puntos de avance, posiciones, fuertes a atacar o defender) aparecen marcados, en el borde si están lejos. Solo se ven las unidades cercanas.'),
  // -------------------------------------------------------------- survival
  E('hunger', 'survival', 'Hunger and food',
    'Hunger slowly drops. Hunt animals, cook the meat on a campfire and eat it (right click with food). Starving makes you sick and, in the end, kills you. Your own forts feed you while you are inside, and their ration crates (E) give food.',
    'Hambre y comida', 'El hambre baja poco a poco. Caza animales, cocina la carne en una hoguera y cómela (clic derecho con la comida). Pasar hambre te enferma y al final te mata. Tus fuertes te alimentan mientras estás dentro y sus cajas de raciones (E) dan comida.'),
  E('hunting', 'survival', 'Hunting',
    'Animals hear you running and flee. Crouch and approach slowly from behind. A knife kills quietly; guns are loud and scare everything nearby.',
    'Caza', 'Los animales te oyen correr y huyen. Agáchate y acércate despacio por detrás. El cuchillo mata en silencio; las armas de fuego hacen ruido y espantan a todo lo cercano.'),
  E('campfire', 'survival', 'Campfires and crafting',
    'Light a campfire with flint and steel. E near a campfire opens crafting: weapons, ammunition, TNT, grenades, rafts and more. K opens simple crafting anywhere.',
    'Hogueras y fabricación', 'Enciende una hoguera con pedernal y eslabón. E junto a una hoguera abre la fabricación: armas, munición, TNT, granadas, balsas y más. K abre la fabricación sencilla en cualquier sitio.'),
  E('health', 'survival', 'Health and medkits',
    'Health comes back slowly while you are well fed. Medkits heal at once. Falls from high up hurt.',
    'Salud y botiquines', 'La salud vuelve poco a poco si estás bien alimentado. Los botiquines curan al instante. Las caídas desde lo alto hacen daño.'),
  // ---------------------------------------------------------------- combat
  E('weapons', 'combat', 'Weapons',
    'Knife (silent, deadly from behind), pistol, bolt-action rifle, submachine gun and sniper rifle. Guns need iron to craft. Crouching and standing still make you more accurate.',
    'Armas', 'Cuchillo (silencioso, letal por la espalda), pistola, fusil de cerrojo, subfusil y fusil de francotirador. Las armas se fabrican con hierro. Agacharse y estar quieto mejora la puntería.'),
  E('scope', 'combat', 'Scope and binoculars',
    'Z (or right click with the sniper rifle) brings the scope up: a circular view with a fine reticle and a blurred dark surround, zooming smoothly. Without the sniper rifle, Z uses binoculars. Your aim sways with your breathing; hold Shift to steady it for a few seconds. Z again lowers it. Ordinary guns keep the normal crosshair and the knife a dot.',
    'Mira y prismáticos', 'Z (o clic derecho con el fusil de francotirador) sube la mira: una vista circular con retícula fina y el borde oscuro y borroso, con zoom suave. Sin el fusil de francotirador, Z usa los prismáticos. La puntería se mueve con la respiración; mantén Mayús para estabilizarla unos segundos. Z de nuevo la baja. Las demás armas usan la mira normal y el cuchillo un punto.'),
  E('grenades', 'combat', 'Grenades and smoke',
    'Left click throws. Grenades explode after a short fuse; smoke grenades hide you from enemy eyes.',
    'Granadas y humo', 'El clic izquierdo lanza. Las granadas explotan tras una mecha corta; las de humo te ocultan de los ojos enemigos.'),
  E('tnt', 'combat', 'TNT',
    'Place TNT and light it with flint and steel, or shoot it. It blows craters but spares fort walls; three charges (or twelve grenades) bring a fort door down. Walk into enemy TNT to pull its wires.',
    'TNT', 'Coloca TNT y enciéndelo con pedernal y eslabón, o dispárale. Abre cráteres pero respeta los muros de los fuertes; tres cargas (o doce granadas) derriban la puerta de un fuerte. Acércate al TNT enemigo para arrancarle los cables.'),
  E('tank', 'combat', 'The tank',
    'A rare enemy tank roams the land. Bullets barely scratch it; use grenades and TNT. Its commander bails out when it burns.',
    'El tanque', 'Un raro tanque enemigo recorre el terreno. Las balas apenas lo arañan; usa granadas y TNT. Su comandante salta fuera cuando arde.'),
  // ----------------------------------------------------------------- squad
  E('squad', 'squad', 'Your squad',
    'In Play with Allies you lead a squad of any size, from a few soldiers to everyone. Taking too many soldiers away leaves your forts weakly guarded. The squad list under the radar shows each soldier, his order and his health.',
    'Tu escuadra', 'En Jugar con aliados diriges una escuadra de cualquier tamaño, desde unos pocos soldados hasta todos. Llevarte a demasiados deja tus fuertes mal defendidos. La lista bajo el radar muestra a cada soldado, su orden y su salud.'),
  E('wheel', 'squad', 'The order wheel',
    'Q opens the order wheel. Move the mouse toward an order and click, or press its number. On phones, use the contextual Follow me and Orders buttons instead. Orders: Follow me, Hold position, Defend the base, Take cover, Spread out, Advance here and Attack this fort.',
    'La rueda de órdenes', 'Q abre la rueda de órdenes. Mueve el ratón hacia una orden y haz clic, o pulsa su número. En el móvil se usan los botones contextuales Sígueme y Órdenes. Órdenes: Seguidme, Mantened la posición, Defended la base, A cubierto, Dispersaos, Avanzad aquí, Atacad este fuerte y la formación.'),
  E('targeting', 'squad', 'Aiming orders',
    'Orders use what you look at when you open the wheel: Advance goes to that spot, Attack goes for that fort (or the nearest enemy fort), Defend goes to that allied fort (or the nearest one).',
    'Órdenes con puntería', 'Las órdenes usan lo que miras al abrir la rueda: Avanzad va a ese punto, Atacad va a ese fuerte (o al fuerte enemigo más cercano), Defended va a ese fuerte aliado (o al más cercano).'),
  E('recipients', 'squad', 'Who gets the order',
    'G adds the soldier you aim at to a selected group (G again removes him; G at nothing clears the group). Orders go to the selected group; with no group, to the soldier you aim at; otherwise to the whole squad. "Follow me" to the whole squad also gathers allies nearby who are not guarding a fort. Aim at a soldier and press 9 in the wheel to talk to him (ask for iron or his gear).',
    'Quién recibe la orden', 'G añade al soldado al que apuntas a un grupo elegido (G otra vez lo quita; G sin apuntar a nadie borra el grupo). Las órdenes van al grupo elegido; sin grupo, al soldado al que apuntas; si no, a toda la escuadra. "Seguidme" a toda la escuadra también reúne a los aliados cercanos que no guardan un fuerte. Apunta a un soldado y pulsa 9 en la rueda para hablar con él (pedirle hierro o su equipo).'),
  E('orders', 'squad', 'What each order does',
    'Your orders always come first, also in the middle of a fight, and each one lasts until you give another. Follow me: they walk in single file behind you. Hold position: they stay exactly where they are, even if you leave. Defend the base: they go to the fort and patrol it. Take cover: each runs to the nearest cover from the enemy and stays there. Spread out: they spread out a few metres apart around where they are and hold there. Advance here: they move to the spot and hold it. Attack this fort: they go to the door, blow it and storm the fort, then defend it. Under any order they shoot back from where the order puts them, but never leave it on their own. Follow me brings them back behind you. Every soldier answers on the radio and his marker changes.',
    'Qué hace cada orden', 'Tus órdenes siempre van primero, también en plena batalla, y cada una dura hasta que des otra. Seguidme: caminan en fila india detrás de ti. Mantened la posición: se quedan exactamente donde están, aunque te vayas. Defended la base: van al fuerte y patrullan. A cubierto: cada uno corre a la cobertura más cercana frente al enemigo y se queda allí. Dispersaos: se separan unos metros alrededor de donde están y se quedan ahí. Avanzad aquí: van al punto y lo mantienen. Atacad este fuerte: van a la puerta, la vuelan, asaltan el fuerte y luego lo defienden. Con cualquier orden responden al fuego desde donde la orden los pone, pero nunca lo abandonan por su cuenta. Seguidme los vuelve a poner detrás de ti. Cada soldado responde por radio y cambia su marcador.'),
  E('formation', 'squad', 'Follow me: single file',
    'When following you, your soldiers walk in single file directly behind you along the exact path you took, at your pace and with steady spacing. They never circle you, get in front of you or block your view. When you stop they stop, and when you crouch they crouch. They follow you through tunnels, holes and caves, climb out where you climbed out, jump in where you jumped in and dive with you under water (they never drown). They do not act on their own: when enemies appear or shoot, they keep following and shoot back as they walk. They leave the line only when you give another order (Hold position, Defend the base, Take cover, Spread out, Advance here, Attack this fort). A soldier who gets stuck finds another way; if that fails he catches up behind you where you are not looking. Nobody stands in a doorway.',
    'Seguidme: fila india', 'Cuando te siguen, tus soldados caminan en fila india justo detrás de ti, por el mismo camino que has hecho, a tu ritmo y a distancia constante. Nunca te rodean, no se ponen delante ni te tapan la vista. Si te paras, se paran; si te agachas, se agachan. Te siguen por túneles, agujeros y cuevas, trepan por donde trepaste, saltan por donde saltaste y bucean contigo (nunca se ahogan). No actúan por su cuenta: cuando aparece o dispara el enemigo, siguen detrás de ti y responden al fuego mientras caminan. Solo dejan la fila cuando das otra orden (Mantened la posición, Defended la base, A cubierto, Dispersaos, Avanzad aquí, Atacad este fuerte). Si un soldado se atasca busca otro camino; si no lo encuentra, aparece detrás de ti donde no estás mirando. Nadie se queda en una puerta.'),
  E('underfire', 'squad', 'Under fire',
    'Each allied soldier follows one rule, in this order: first your orders, then following you, and only when he has neither does he act on his own. Soldiers you have given an order stay with it and fire from where it puts them; soldiers following you keep following. Allies who are not following you and have no order take cover, return fire, patrol and defend by themselves. Orders can be given at any time, also during a fight.',
    'Bajo fuego', 'Cada soldado aliado sigue una regla, por este orden: primero tus órdenes, después seguirte, y solo cuando no tiene ninguna de las dos actúa por su cuenta. Los soldados con una orden la cumplen y disparan desde donde la orden los pone; los que te siguen siguen detrás de ti. Los aliados que no te siguen y no tienen orden se cubren, responden al fuego, patrullan y defienden solos. Puedes dar órdenes en cualquier momento, también en pleno combate.'),
  E('fallen', 'squad', 'Fallen allies',
    'Defeated allies come back some time later near one of your forts and walk back to it. They are no longer part of your squad; recruit them again with "Follow me".',
    'Aliados caídos', 'Los aliados abatidos vuelven al rato cerca de uno de tus fuertes y caminan hasta él. Ya no forman parte de tu escuadra; vuelve a reclutarlos con "Seguidme".'),
  // ----------------------------------------------------------------- forts
  E('forts', 'forts', 'Forts',
    'Forts are always lit inside. Their doors open only for their owners. A fort is captured when its defenders are gone or surrender (officer down, or door blown and outnumbered) and you or your allies are inside. Your forts feed you and sound a siren when attacked.',
    'Fuertes', 'Los fuertes siempre están iluminados por dentro. Sus puertas solo se abren para sus dueños. Se captura un fuerte cuando sus defensores caen o se rinden (oficial abatido, o puerta volada y en inferioridad) y tú o tus aliados estáis dentro. Tus fuertes te alimentan y hacen sonar una sirena si los atacan.'),
  E('guards', 'forts', 'Garrisons',
    'Every fort keeps guards that never leave it. The rest of its soldiers may be sent out in attack squads.',
    'Guarniciones', 'Cada fuerte tiene guardias que nunca salen. El resto de sus soldados puede salir en escuadras de ataque.'),
  // ----------------------------------------------------------------- enemy
  E('raids', 'enemy', 'Attack squads',
    'The enemy sends squads of about 5-6 soldiers from its forts to attack yours. There is no warning when they leave; you only see them on the radar once they are close. Difficulty sets how big and how frequent the squads are. Attacks are lighter by day and heavier at night.',
    'Escuadras de ataque', 'El enemigo envía escuadras de unos 5-6 soldados desde sus fuertes contra los tuyos. No hay aviso cuando salen; solo los ves en el radar cuando están cerca. La dificultad decide su tamaño y frecuencia. Los ataques son más ligeros de día y más fuertes de noche.'),
  E('patrols', 'enemy', 'Patrols',
    'Both sides keep patrols of about 4-6 soldiers out in the field at all times. Each patrol leaves a fort with a purpose: it walks toward a nearby fort, a river crossing, or the area around the other side\'s fort or your cabin, then returns home. Some guards always stay in every fort. Difficulty sets how many patrols there are and how big they are; in Day only worlds they are as active as at night. There is no warning when they leave: you meet them in the field or see them on the radar.',
    'Patrullas', 'Los dos bandos mantienen siempre patrullas de unos 4-6 soldados en el terreno. Cada patrulla sale de un fuerte con un propósito: va hacia un fuerte cercano, un paso del río o los alrededores de un fuerte del otro bando o de tu cabaña, y luego vuelve a casa. En cada fuerte siempre quedan guardias. La dificultad decide cuántas patrullas hay y su tamaño; en los mundos de Solo de día están igual de activas que de noche. No hay aviso cuando salen: te las encuentras en el terreno o las ves en el radar.'),
  E('fortpaths', 'forts', 'How soldiers move in forts',
    'Soldiers only enter and leave a fort through its door, walking around the walls to reach it and waiting their turn if the doorway is busy. Guards reach the rampart by the ladders and climb down the same way, for example when you tell them to follow you.',
    'Cómo se mueven los soldados en los fuertes', 'Los soldados solo entran y salen de un fuerte por la puerta: rodean los muros para llegar a ella y esperan su turno si el paso está ocupado. Los guardias suben a la muralla por las escaleras de mano y bajan por ellas, por ejemplo cuando les ordenas que te sigan.'),
  E('tactics', 'enemy', 'Enemy tactics',
    'In the field enemies spread out, take cover behind trees, walls and terrain, and shoot from there. Sappers set charges at fort doors. Flank them: cover only works from one side.',
    'Tácticas enemigas', 'En campo abierto el enemigo se dispersa, se cubre tras árboles, muros y el terreno y dispara desde ahí. Los zapadores ponen cargas en las puertas. Flanquéalos: la cobertura solo protege por un lado.'),
  E('cabin', 'enemy', 'The cabin (Play Alone)',
    'Playing alone, enemy squads attack the forts you captured and also come for your cabin: they surround it and wait for you to come out.',
    'La cabaña (Jugar solo)', 'Jugando solo, las escuadras enemigas atacan los fuertes que capturaste y también van a tu cabaña: la rodean y esperan a que salgas.'),
  E('respawn', 'enemy', 'Defeated enemies',
    'Defeated enemies come back near one of their forts, walk back to it and attack again later, so their numbers stay the same. If they have no forts left, survivors scatter, regroup, craft weapons and counterattack.',
    'Enemigos abatidos', 'Los enemigos abatidos vuelven cerca de uno de sus fuertes, caminan hasta él y atacan otra vez más tarde, así que su número no cambia. Si no les quedan fuertes, los supervivientes se dispersan, se reagrupan, fabrican armas y contraatacan.'),
  // ------------------------------------------------------------------ game
  E('modes', 'game', 'Two games',
    'The start screen offers two games that share the same engine, settings and language: Mighty Men o\' War (War) and Town Life. In War you survive, build, hunt and fight, alone (you start in a cabin) or with allies, with its own menu and save slots. Town Life is a peacetime countryside game with one persistent world. The old Peace mode has been removed and its saved worlds deleted.',
    'Dos juegos', 'La pantalla de inicio ofrece dos juegos que comparten el mismo motor, los ajustes y el idioma: Mighty Men o\' War (Guerra) y Town Life (Vida en el pueblo). En Guerra sobrevives, construyes, cazas y combates, solo (empiezas en una cabaña) o con aliados, con su propio menú y sus partidas guardadas. Town Life es un juego de campo en tiempos de paz con un único mundo persistente. El antiguo modo Paz se ha eliminado y sus mundos guardados se han borrado.'),
  E('timeofday', 'game', 'Time of day',
    'When you start a War game you choose "Day and night" (a full cycle: lighter enemy attacks by day, heavier at night) or "Day only" (always daylight, but the enemy attacks constantly at night-time strength). The choice is saved with the world.',
    'Hora del día', 'Al empezar una partida de Guerra eliges "Día y noche" (ciclo completo: ataques más ligeros de día y más fuertes de noche) o "Solo de día" (siempre hay luz, pero el enemigo ataca sin parar con la fuerza de la noche). La elección se guarda con el mundo.'),
  E('difficulty', 'game', 'Difficulty',
    'From Beginner to Impossible: more and bigger enemy squads, scarcer food and forts farther apart.',
    'Dificultad', 'De Principiante a Imposible: más escuadras enemigas y más grandes, menos comida y fuertes más alejados.'),
  E('quality', 'game', 'Graphics quality',
    'Low, Medium or High. Higher quality draws smoother soldiers, fully animates more of them at once and shows their kit and faces from farther away. Lower quality runs better on slower devices.',
    'Calidad gráfica', 'Baja, Media o Alta. Más calidad dibuja soldados más suaves, anima por completo a más a la vez y muestra su equipo y cara desde más lejos. Menos calidad va mejor en equipos lentos.'),
  E('saving', 'game', 'Saving',
    'The world saves itself every minute and when you quit to the menu. Several worlds can be kept; load or delete them from Load Game.',
    'Guardar', 'El mundo se guarda solo cada minuto y al salir al menú. Puedes tener varios mundos; cárgalos o bórralos desde Cargar partida.'),
  E('language', 'game', 'Language',
    'English or Spanish, from the start screen, the War menu or Settings.',
    'Idioma', 'Inglés o español, desde la pantalla de inicio, el menú de Guerra o los Ajustes.'),

  // ------------------------------------------------------------- Town Life
  E('t_world', 'town', 'Town Life: your world',
    'A peaceful 1940s countryside with one world that is always kept (no save slots). It saves itself about every minute and when you leave, writing only what changed, and keeps a backup of the last good save. "Start over" on the Town Life menu deletes it after you confirm. You start with no money, a shovel and flint and steel, in a cottage that cannot be destroyed, with an ever-burning fire, a bed, a storage chest, a fenced pen and a small garden.',
    'Town Life: tu mundo', 'Un campo tranquilo de los años cuarenta con un único mundo que siempre se guarda (sin ranuras). Se guarda solo cada minuto más o menos y al salir, escribiendo solo lo que ha cambiado, y guarda una copia de seguridad de la última partida buena. "Empezar de cero" en el menú de Town Life lo borra tras confirmarlo. Empiezas sin dinero, con una pala y pedernal y eslabón, en una casa indestructible con un fuego que nunca se apaga, una cama, un baúl, un corral vallado y un pequeño huerto.'),
  E('t_seasons', 'town', 'Seasons and weather',
    'Days and nights pass, and every three days the season changes: spring, summer, autumn and winter. It rains in spring, summer and autumn; leaves turn orange in autumn; in winter snow covers the ground, lakes and rivers freeze (dig the ice to reach the water) and nothing grows.',
    'Estaciones y tiempo', 'Pasan los días y las noches, y cada tres días cambia la estación: primavera, verano, otoño e invierno. Llueve en primavera, verano y otoño; en otoño las hojas se vuelven naranjas; en invierno la nieve cubre el suelo, lagos y ríos se hielan (cava el hielo para llegar al agua) y nada crece.'),
  E('t_blocks', 'town', 'Materials',
    'Grass over dirt, logs and planks, stone about three blocks down, iron in the stone, very rare gold that glints faintly, sand by the water, clay in river beds, glass, thatch, bricks, charcoal and fences. At a campfire: wood becomes charcoal, clay and charcoal become bricks, sand and charcoal become glass, wheat becomes thatch or bread.',
    'Materiales', 'Hierba sobre tierra, troncos y tablones, piedra unos tres bloques bajo tierra, hierro en la piedra, oro muy escaso que brilla un poco, arena junto al agua, arcilla en los lechos de los ríos, vidrio, paja, ladrillos, carbón y vallas. En una hoguera: la madera da carbón, arcilla y carbón dan ladrillos, arena y carbón dan vidrio, el trigo da paja o pan.'),
  E('t_farm', 'town', 'Farming',
    'Buy seeds at the general store or the market (or take them from the village fields, which is theft). Sow them on grass, dirt or farmland. Crops need water: fill a bucket at any water and use it on the crops (rain waters them too). Crops left dry wilt and nearly die. Nothing grows in winter. Dig up ripe crops to harvest them; you also get seeds back.',
    'Cultivar', 'Compra semillas en la tienda de ultramarinos o en el mercado (o cógelas de los campos del pueblo, que es robar). Siémbralas en hierba, tierra o tierra de cultivo. Los cultivos necesitan agua: llena un cubo en cualquier agua y úsalo sobre ellos (la lluvia también los riega). Sin agua se marchitan y casi mueren. En invierno nada crece. Cava los cultivos maduros para cosecharlos; también recuperas semillas.'),
  E('t_animals', 'town', 'Livestock',
    'Buy chickens, piglets and calves at the market stall: they go to your pen. Hens lay eggs in the pen, cows give milk once a day (with a bucket), pigs give meat. The village animals belong to the village: killing them is a crime.',
    'Ganado', 'Compra gallinas, lechones y terneros en el puesto del mercado: van a tu corral. Las gallinas ponen huevos en el corral, las vacas dan leche una vez al día (con un cubo) y los cerdos dan carne. Los animales del pueblo son del pueblo: matarlos es un delito.'),
  E('t_hunt', 'town', 'Hunting and skinning',
    'Weapons are crafted at a campfire as in War, or bought at the hunting store. Deer and birds live in the woods and fields; when one is killed another turns up somewhere else. Bears are rare in summer and many in winter: they take several shots and fight back. Skin a carcass to get meat and a hide (a bear hide is worth a lot).',
    'Caza y desollado', 'Las armas se fabrican en una hoguera como en Guerra, o se compran en la tienda de caza. Ciervos y pájaros viven en bosques y campos; cuando cae uno, aparece otro en otra parte. Los osos son raros en verano y abundan en invierno: aguantan varios disparos y atacan. Desuella una pieza para conseguir carne y piel (la de oso vale mucho).'),
  E('t_shops', 'town', 'Shops and money',
    'The butcher, the general store, the hunting store and the market stall are always open; their keepers stay at their shops. Buy, or sell what you have gathered, grown or hunted. Your honor changes the prices.',
    'Tiendas y dinero', 'La carnicería, la tienda de ultramarinos, la tienda de caza y el puesto del mercado siempre están abiertos; sus tenderos se quedan en la tienda. Compra, o vende lo que hayas recogido, cultivado o cazado. Tu honor cambia los precios.'),
  E('t_favors', 'town', 'Favors',
    'Walk up to a villager and ask for a favor: bring them some goods or carry a letter to someone. Favors pay coins, raise your honor and lower your bounty. One job at a time, two days to finish it.',
    'Favores', 'Acércate a un vecino y pídele un favor: llevarle algo o entregar una carta a alguien. Los favores dan monedas, suben tu honor y bajan la recompensa por tu cabeza. Un encargo cada vez, con dos días para terminarlo.'),
  E('t_law', 'town', 'Honor, witnesses and the law',
    'Honor changes prices, greetings and favors. A crime (stealing crops or animals, hurting or killing someone) only counts if someone sees it: a warning names the witness, who runs to the sheriff; stop them or let them report. A report adds to your bounty and a posse of townspeople forms (bigger bounty, bigger posse). They search where you were last seen, take cover and give up if you stay hidden long enough. They can come into your cottage. They question you first: Surrender, Pay the fine, Talk, Run or Fight; they only shoot if you resist or run. Jail costs the fine, your stolen goods and your scuba gear, and you wake at home a day later with your crops nearly dead. Clear your name by paying the fine (also to the sheriff), turning yourself in, laying low for a few quiet days or doing favors.',
    'Honor, testigos y la ley', 'El honor cambia los precios, los saludos y los favores. Un delito (robar cultivos o animales, herir o matar a alguien) solo cuenta si alguien lo ve: un aviso nombra al testigo, que corre a ver al sheriff; puedes detenerlo o dejar que te denuncie. La denuncia aumenta la recompensa por tu cabeza y se forma una partida de vecinos (más recompensa, más vecinos). Buscan donde te vieron por última vez, se cubren y se rinden si te escondes el tiempo suficiente. Pueden entrar en tu casa. Primero te interrogan: Entregarte, Pagar la multa, Convencerlos, Huir o Pelear; solo disparan si te resistes o huyes. La cárcel te cuesta la multa, lo robado y el equipo de buceo, y despiertas en casa un día después con los cultivos casi muertos. Limpia tu nombre pagando la multa (también al sheriff), entregándote, pasando unos días tranquilos o haciendo favores.'),
  E('t_death', 'town', 'Hunger, injury and sleep',
    'There is no game over: if you are killed or starve you wake up in your cottage (scuba gear is lost). Sleep in your bed in the evening or at night to wake the next morning.',
    'Hambre, heridas y sueño', 'No hay fin de partida: si mueres o te mueres de hambre, despiertas en tu casa (pierdes el equipo de buceo). Duerme en tu cama por la tarde o de noche para despertar a la mañana siguiente.'),
  E('t_sound', 'town', 'Voices, music and sounds',
    'Nobody speaks aloud in either game: townspeople and soldiers talk in text bubbles with a short mumble or radio tone. Town Life has its own calm folk music, made live by the game, plus birdsong, crickets, owls, wind and animal sounds. In War, grenades and lit charges sound an alarm, show a warning and flash on the radar.',
    'Voces, música y sonidos', 'Nadie habla en voz alta en ningún juego: vecinos y soldados hablan con bocadillos de texto y un murmullo o un tono de radio. Town Life tiene su propia música folk tranquila, creada en directo por el juego, además de pájaros, grillos, búhos, viento y animales. En Guerra, las granadas y las cargas encendidas hacen sonar una alarma, muestran un aviso y parpadean en el radar.'),
  E('t_perf', 'game', 'Performance',
    'Settings > Performance: Smooth shortens the view and lightens effects for a steadier frame rate on phones. Only nearby areas are drawn, far ones are freed from memory, and far-away people and animals rest. A hidden frame counter: see Controls.',
    'Rendimiento', 'Ajustes > Rendimiento: Fluido acorta la vista y aligera los efectos para que el móvil vaya más suave. Solo se dibuja lo cercano, lo lejano se libera de la memoria y la gente y los animales lejanos descansan. Hay un contador de fotogramas oculto: mira Controles.'),
  E('t_controls', 'town', 'Town Life controls', 'Nearby actions appear on screen.', 'Controles de Town Life', 'Las acciones cercanas aparecen en pantalla.'),
  // ------------------------------------------------------------- additions
  E('controls', 'basics', 'Controls',
    'Keyboard and mouse: WASD move, Shift run, C crouch, Space jump/swim, left click dig/attack, right click place/use, 1-9 hotbar, E campfire/rations/chest, Q order wheel, G select soldier, T follow me, Y ask for iron, U ask for a weapon, F flashlight, Z scope/binoculars, M war map, I inventory, K craft, Esc pause. Phones: left thumb moves, right side looks; buttons for jump, use, action, run, crouch, zoom, light, bag, craft and map. Squad buttons appear only when they make sense.',
    'Controles', 'Teclado y ratón: WASD moverse, Mayús correr, C agacharse, Espacio saltar/nadar, clic izquierdo cavar/atacar, clic derecho colocar/usar, 1-9 barra, E hoguera/raciones/baúl, Q rueda de órdenes, G elegir soldado, T sígueme, Y pedir hierro, U pedir un arma, F linterna, Z mira/prismáticos, M mapa de guerra, I inventario, K fabricar, Esc pausa. Móvil: el pulgar izquierdo mueve y el lado derecho mira; hay botones para saltar, usar, acción, correr, agacharse, zoom, luz, bolsa, fabricar y mapa. Los botones de escuadra solo aparecen cuando tienen sentido.'),
  E('blocks', 'basics', 'Blocks',
    'Dirt, mud, rubble, logs, planks, leaves, stone, iron ore, sandbags, barbed wire and TNT. Sandbags and wire make good cover and obstacles; wire slows everyone and cuts enemies. Iron ore is used to craft guns.',
    'Bloques', 'Tierra, barro, escombros, troncos, tablones, hojas, piedra, mineral de hierro, sacos terreros, alambre de espino y TNT. Los sacos y el alambre son buena cobertura y obstáculo; el alambre frena a todos y hiere al enemigo. El hierro sirve para fabricar armas.'),
  E('nearforts', 'forts', 'Building near forts',
    'Built-in forts cannot be damaged or changed. Outside a fort you can dig and build anywhere, right up against its walls and in front of its door: trenches, sandbags, cover, and TNT at the door. Inside a fort the only thing you can place is a campfire, for crafting.',
    'Construir junto a los fuertes', 'Los fuertes no se pueden dañar ni modificar. Fuera de un fuerte puedes cavar y construir donde quieras, pegado a sus muros y delante de la puerta: trincheras, sacos terreros, cobertura y TNT en la puerta. Dentro de un fuerte solo puedes colocar una hoguera para fabricar.'),
  E('swimming', 'basics', 'Swimming and crossing water',
    'Swimming is slow and you can only use a pistol or a knife in the water. Soldiers follow the same rules: they prefer bridges and shallow fords, and swim only when they must, so they are exposed while crossing. Soldiers travelling on their own also use the underground tunnels between forts.',
    'Nadar y cruzar el agua', 'Nadar es lento y en el agua solo puedes usar pistola o cuchillo. Los soldados siguen las mismas reglas: prefieren puentes y vados poco profundos y solo nadan cuando no queda otra, así que están expuestos al cruzar. Los soldados que viajan por su cuenta también usan los túneles subterráneos entre fuertes.'),
  E('diving', 'basics', 'Diving and air',
    'In deep water you sink and move freely in every direction under water: up to swim up, down to dive. You can switch between diving and swimming on the surface (see Controls). Without gear you have about 20 seconds of air: an air bar appears, the view turns blue and dim, sound is muffled and bubbles rise. When the air runs out you lose health until you surface. Only the knife and the pistol work under water. Your followers dive with you and never drown; other soldiers stay on the surface.',
    'Buceo y aire', 'En agua profunda te hundes y bajo el agua te mueves libremente en todas direcciones: hacia arriba para subir, hacia abajo para bucear. Puedes cambiar entre bucear y nadar en la superficie (mira Controles). Sin equipo tienes unos 20 segundos de aire: aparece una barra de aire, la vista se vuelve azul y oscura, el sonido se apaga y suben burbujas. Cuando se acaba el aire pierdes salud hasta que sales a la superficie. Bajo el agua solo funcionan el cuchillo y la pistola. Los soldados que te siguen bucean contigo y nunca se ahogan; los demás se quedan en la superficie.'),
  E('scuba', 'survival', 'Scuba gear',
    'Craft scuba gear at a campfire (4 iron and 1 wood). While you carry it you have unlimited air under water. It is lost every time you are killed, so craft a new set afterwards.',
    'Equipo de buceo', 'Fabrica el equipo de buceo en una hoguera (4 de hierro y 1 de madera). Mientras lo lleves tienes aire ilimitado bajo el agua. Se pierde cada vez que te matan, así que fabrica otro después.'),
  E('trapped', 'enemy', 'Soldiers stuck in holes',
    'A soldier who falls into a hole first tries to climb out or walk around it. If he is still stuck after about 10 seconds he counts as defeated and comes back near one of his side\'s forts.',
    'Soldados atrapados en agujeros', 'Un soldado que cae en un agujero intenta trepar o rodearlo. Si a los 10 segundos sigue atrapado cuenta como abatido y vuelve cerca de uno de los fuertes de su bando.'),
  E('squadphone', 'squad', 'Squad commands on phones',
    'There are no permanent squad buttons. Stand beside an allied soldier and a "Follow me" button appears: it recruits him and the allies close to you, and also calls back soldiers who are holding or guarding. While you have a squad, a small Orders button opens a short menu: Follow me, Hold position, Defend the base, Spread out, Take cover, Attack this fort. It works at any time, also in the middle of a fight. "Ask for iron" and "Ask for a weapon" appear beside a soldier.',
    'Órdenes de escuadra en el móvil', 'No hay botones de escuadra fijos. Ponte junto a un soldado aliado y aparece "Sígueme": lo recluta a él y a los aliados cercanos, y también llama a los que mantienen posición o hacen guardia. Mientras tengas escuadra, un pequeño botón Órdenes abre un menú corto: Seguidme, Mantened la posición, Defended la base, Dispersaos, A cubierto, Atacad este fuerte. Funciona en cualquier momento, también en pleno combate. "Pedir hierro" y "Pedir un arma" aparecen junto a un soldado.'),
  E('cabinfull', 'survival', 'The cabin',
    'Playing alone you start in a log cabin that cannot be destroyed and that enemies cannot enter. It has an ever-burning campfire for crafting, a bed and a storage chest. Iron is very plentiful around it. If you are defeated you wake up at the bed with only what you left in the chest. Starving (about 5 in-game days without food) ends the game.',
    'La cabaña', 'Jugando solo empiezas en una cabaña de troncos indestructible en la que el enemigo no puede entrar. Tiene una hoguera que nunca se apaga para fabricar, una cama y un baúl. Alrededor hay muchísimo hierro. Si caes, despiertas junto a la cama solo con lo que dejaste en el baúl. Morir de hambre (unos 5 días sin comer) termina la partida.'),
  E('warmap', 'basics', 'War map',
    'M (or MAP on phones, or the pause menu) opens the war map: every fort in its owner\'s colour (allied, enemy, unclaimed), your position, the cabin when playing alone and the current mission objective.',
    'Mapa de guerra', 'M (o MAPA en el móvil, o el menú de pausa) abre el mapa de guerra: todos los fuertes con el color de su dueño (aliado, enemigo, sin dueño), tu posición, la cabaña si juegas solo y el objetivo de la misión.'),
  E('music', 'game', 'Music',
    '"Marines\' Hymn", played by the United States Marine Band, plays quietly on the splash screen and the menus (after your first tap or click), loops smoothly and stops during play. Change its volume or mute it in Settings, or use the speaker icon on the start screen. Your choice is remembered.',
    'Música', 'En la pantalla de presentación y en los menús suena en voz baja el "Marines\' Hymn" interpretado por la Banda de la Infantería de Marina de los Estados Unidos (tras tu primer toque o clic); se repite sin cortes y se detiene al jugar. Cambia su volumen o silénciala en Ajustes, o usa el icono del altavoz de la pantalla de inicio. Se recuerda tu elección.'),
  E('settings', 'game', 'Settings',
    'Language, graphics quality, render distance, sound volume, music volume and mute, mouse sensitivity and invert, blood on/off, minimap on/off and size and touch button size.',
    'Ajustes', 'Idioma, calidad gráfica, distancia de dibujado, volumen del sonido, volumen y silencio de la música, sensibilidad e inversión del ratón, sangre sí/no, minimapa sí/no y tamaño y tamaño de los botones táctiles.'),
  E('statsm', 'game', 'Statistics',
    'Days survived, forts captured and lost, enemies defeated, animals hunted, longest survival alone, missions completed and medals, with War statistics per difficulty. They can be reset from the Statistics screen.',
    'Estadísticas', 'Días sobrevividos, fuertes capturados y perdidos, enemigos abatidos, animales cazados, supervivencia más larga en solitario, misiones cumplidas y medallas, con las de guerra por dificultad. Se pueden reiniciar desde la pantalla de Estadísticas.'),
  E('slots', 'game', 'Save slots',
    'Each saved War world remembers its squad choice, game type, difficulty, time of day and mission progress. Delete one world or all of them from Load Game. Worlds from older versions are marked outdated and rebuilt when loaded.',
    'Partidas guardadas', 'Cada mundo de Guerra guardado recuerda la escuadra, el tipo de partida, dificultad, hora del día y el progreso de la misión. Borra un mundo o todos desde Cargar partida. Los mundos de versiones antiguas aparecen como antiguos y se reconstruyen al cargarlos.'),
  E('app', 'game', 'Install and play offline',
    'The game can be installed as an app from your browser menu and then plays offline. When a new version is ready, a notice offers to reload.',
    'Instalar y jugar sin conexión', 'El juego se puede instalar como aplicación desde el menú del navegador y después funciona sin conexión. Cuando hay una versión nueva, un aviso te ofrece recargar.'),
  E('credits', 'game', 'Credits',
    'Mighty Men o\' War. Original game, textures and sounds made for this game. Title art and badge by the game\'s creator (sources in art/); lettering rendered with the Anton typeface (SIL Open Font License). Menu music: "Marines\' Hymn", composition by Jacques Offenbach (public domain); performed by the United States Marine Band; the recording is a work of the U.S. federal government and is in the public domain. Source: Internet Archive, item "MarinesHymn". 3D engine: three.js.',
    'Créditos', 'Mighty Men o\' War. Juego, texturas y sonidos originales, hechos para este juego. Ilustración del título e insignia del creador del juego (originales en art/); letras con la tipografía Anton (SIL Open Font License). Música del menú: "Marines\' Hymn", composición de Jacques Offenbach (dominio público); interpretada por la Banda de la Infantería de Marina de los Estados Unidos (United States Marine Band); la grabación es una obra del Gobierno federal de los EE. UU. y es de dominio público. Fuente: Internet Archive, elemento "MarinesHymn". Motor 3D: three.js.'),
  E('opmis', 'missions', 'Open World or Missions',
    'Open World is the free, endless game: no assigned missions, you set your own goals. Missions set up the world for one task; pick one from the list and replay it as often as you like. After a mission you can replay it, pick another or carry on in Open World.',
    'Mundo abierto o misiones', 'El mundo abierto es la partida libre y sin fin: sin misiones asignadas, tú pones tus metas. En las misiones el mundo se prepara para una tarea; elige una de la lista y repítela cuando quieras. Al terminar puedes repetirla, elegir otra o seguir en mundo abierto.'),
  E('medals', 'missions', 'Medals',
    'Completing a mission gives a bronze, silver or gold medal depending on how well you did (time left, health, carriers saved and so on). Your best medal shows on the mission list.',
    'Medallas', 'Cumplir una misión da una medalla de bronce, plata u oro según lo bien que lo hayas hecho (tiempo restante, salud, porteadores salvados…). Tu mejor medalla aparece en la lista de misiones.'),
  E('wmissions', 'missions', 'War missions',
    'Take the Fort, Trench Defense, Hold the Fort, Scout the Enemy, Tree Sniper, Bridge Defense, Supply Run, Demolition and Capture Every Fort (hardest difficulties only). Playing alone you get the missions that make sense solo (with smaller versions of Take the Fort and Capture Every Fort); Bridge Defense and Supply Run need allies. Difficulty sets enemy numbers, squad size, time limits and supplies.',
    'Misiones de guerra', 'Tomar el fuerte, Defensa de trinchera, Resistir en el fuerte, Reconocimiento, Francotirador en el árbol, Defensa del puente, Convoy de suministros, Demolición y Capturar todos los fuertes (solo en las dificultades más duras). Jugando solo tienes las misiones que tienen sentido en solitario (con versiones reducidas de Tomar el fuerte y Capturar todos los fuertes); Defensa del puente y Convoy necesitan aliados. La dificultad decide el número de enemigos, el tamaño de las escuadras, los límites de tiempo y los suministros.'),
  E('m_take', 'missions', 'Take the Fort', 'Take the Fort: build a squad and capture the marked enemy fort before time runs out.', 'Tomar el fuerte', 'Tomar el fuerte: forma una escuadra y captura el fuerte enemigo marcado antes de que se acabe el tiempo.'),
  E('m_trench', 'missions', 'Trench Defense', 'Trench Defense: you get time to dig in with your shovel, sandbags and wire, then waves of enemy squads attack until the timer ends.', 'Defensa de trinchera', 'Defensa de trinchera: tienes tiempo para atrincherarte con la pala, sacos y alambre; después atacan oleadas de escuadras hasta que acaba el tiempo.'),
  E('m_hold', 'missions', 'Hold the Fort', 'Hold the Fort: a surprisingly large force tries to blow your door with TNT. Shoot the charges or walk up to them to pull the wires. You lose if the fort is taken.', 'Resistir en el fuerte', 'Resistir en el fuerte: una fuerza sorprendentemente grande intenta volar tu puerta con TNT. Dispara a las cargas o acércate para arrancarles los cables. Pierdes si toman el fuerte.'),
  E('m_scout', 'missions', 'Scout the Enemy', 'Scout the Enemy: watch the marked fort through the binoculars (Z) to count its soldiers, find the officer with the binoculars, then get back to where you started.', 'Reconocimiento', 'Reconocimiento: observa el fuerte marcado con los prismáticos (Z) para contar sus soldados, localiza al oficial con los prismáticos y vuelve al punto de partida.'),
  E('m_sniper', 'missions', 'Tree Sniper', 'Tree Sniper: climb the tree beside you and take out the enemy officer before his squad moves out.', 'Francotirador en el árbol', 'Francotirador en el árbol: sube al árbol de al lado y abate al oficial enemigo antes de que su escuadra se ponga en marcha.'),
  E('m_bridge', 'missions', 'Bridge Defense', 'Bridge Defense: hold your end of a bridge with your squad. If three enemies reach your bank, the mission fails.', 'Defensa del puente', 'Defensa del puente: defiende tu extremo del puente con tu escuadra. Si tres enemigos llegan a tu orilla, la misión fracasa.'),
  E('m_supply', 'missions', 'Supply Run', 'Supply Run: escort three supply carriers to your fort across enemy ground; ambushes are waiting.', 'Convoy de suministros', 'Convoy de suministros: escolta a tres porteadores hasta tu fuerte por terreno enemigo; habrá emboscadas.'),
  E('m_demo', 'missions', 'Demolition', "Demolition: blow open the marked fort's door with TNT (3 charges) or grenades (12) before the timer ends.", 'Demolición', 'Demolición: vuela la puerta del fuerte marcado con TNT (3 cargas) o granadas (12) antes de que acabe el tiempo.'),
  E('m_all', 'missions', 'Capture Every Fort', 'Capture Every Fort: take every enemy fort. A long, very hard mission for Hard and Impossible.', 'Capturar todos los fuertes', 'Capturar todos los fuertes: toma todos los fuertes enemigos. Una misión larga y muy dura, para Difícil e Imposible.'),
];

// Device-specific wording for the entries that mention controls. Phones never
// read about keys or the mouse; computers never read about taps or buttons.
export const MANUAL_DEVICE = {
  pc: {
    t_controls: {
      en: 'Town Life on a computer: E and R do the nearby actions shown on screen (shop, ask for a favor, talk to the sheriff, skin, milk, sleep, campfire). Right click sows seeds, fills and empties the bucket. Left click digs and harvests. F3 shows or hides the frame counter.',
      es: 'Town Life en el ordenador: E y R hacen las acciones cercanas que aparecen en pantalla (tienda, pedir un favor, hablar con el sheriff, desollar, ordeñar, dormir, hoguera). Clic derecho siembra, llena y vacía el cubo. Clic izquierdo cava y cosecha. F3 muestra u oculta el contador de fotogramas.',
    },
    controls: {
      en: 'WASD move, Shift run, C crouch, Space jump (double-tap Space in deep water: dive or swim on the surface; hold Space to swim up, C to swim down), left click dig / attack, right click place / use / scope, 1-9 or the mouse wheel: hotbar, E campfire crafting / ration crates / chest, Q order wheel, G select soldier, T follow me, Y ask for iron, U ask for a weapon, F flashlight, Z scope or binoculars (Shift steadies your aim), M war map, I or Tab inventory, K crafting, Esc pause.',
      es: 'WASD moverse, Mayús correr, C agacharse, Espacio saltar (doble toque de Espacio en agua profunda: bucear o nadar en la superficie; mantén Espacio para subir y C para bajar), clic izquierdo cavar / atacar, clic derecho colocar / usar / mira, 1-9 o la rueda del ratón: barra rápida, E fabricar en la hoguera / cajas de raciones / baúl, Q rueda de órdenes, G elegir soldado, T sígueme, Y pedir hierro, U pedir un arma, F linterna, Z mira o prismáticos (Mayús estabiliza), M mapa de guerra, I o Tab inventario, K fabricar, Esc pausa.',
    },
    wheel: {
      en: 'Q opens the order wheel. Move the mouse toward an order and click, or press its number. Orders: Follow me, Hold position, Defend the base, Take cover, Spread out, Advance here and Attack this fort.',
      es: 'Q abre la rueda de órdenes. Mueve el ratón hacia una orden y haz clic, o pulsa su número. Órdenes: Seguidme, Mantened la posición, Defended la base, A cubierto, Dispersaos, Avanzad aquí y Atacad este fuerte.',
    },
    squadphone: {
      en: 'Beside an allied soldier, small hints appear: T makes him and the allies close to you follow you (it also calls back soldiers who are holding or guarding), Y asks for iron and U asks for a weapon. T with nobody beside you calls your whole squad back behind you. Q opens the order wheel for the rest.',
      es: 'Junto a un soldado aliado aparecen pequeñas indicaciones: T hace que te sigan él y los aliados cercanos (también llama a los que mantienen posición o hacen guardia), Y pide hierro y U pide un arma. T sin nadie al lado llama a toda la escuadra detrás de ti. Q abre la rueda de órdenes para lo demás.',
    },
    warmap: {
      en: 'M (or War map in the pause menu) opens the war map: every fort in its owner\'s colour (allied, enemy, unclaimed), your position, the cabin when playing alone and the current mission objective. M or Close shuts it.',
      es: 'M (o Mapa de guerra en el menú de pausa) abre el mapa de guerra: todos los fuertes con el color de su dueño (aliado, enemigo, sin dueño), tu posición, la cabaña si juegas solo y el objetivo de la misión. M o Cerrar lo cierran.',
    },
    music: {
      en: '"Marines\' Hymn", played by the United States Marine Band, plays quietly on the splash screen and the menus (after your first click or key press), loops smoothly and stops during play. Change its volume or mute it in Settings, or click the speaker icon on the start screen. Your choice is remembered.',
      es: 'En la pantalla de presentación y en los menús suena en voz baja el "Marines\' Hymn" interpretado por la Banda de la Infantería de Marina de los Estados Unidos (tras tu primer clic o tecla); se repite sin cortes y se detiene al jugar. Cambia su volumen o siléncialo en Ajustes, o haz clic en el icono del altavoz de la pantalla de inicio. Se recuerda tu elección.',
    },
    settings: {
      en: 'Language, graphics quality, render distance, sound volume, music volume and mute, mouse sensitivity and invert, blood on/off, minimap on/off and size.',
      es: 'Idioma, calidad gráfica, distancia de dibujado, volumen del sonido, volumen y silencio de la música, sensibilidad e inversión del ratón, sangre sí/no, minimapa sí/no y tamaño.',
    },
  },
  touch: {
    t_controls: {
      en: 'Town Life on a phone: buttons appear for what you can do nearby (shop, ask for a favor, talk to the sheriff, skin, milk, sleep, campfire); tap them. USE sows seeds, fills and empties the bucket. ACTION digs and harvests. Tap the clock three times to show or hide the frame counter.',
      es: 'Town Life en el móvil: aparecen botones con lo que puedes hacer cerca (tienda, pedir un favor, hablar con el sheriff, desollar, ordeñar, dormir, hoguera); tócalos. USAR siembra, llena y vacía el cubo. ACCIÓN cava y cosecha. Toca el reloj tres veces para mostrar u ocultar el contador de fotogramas.',
    },
    move: {
      en: 'Put your left thumb anywhere on the left side and drag to walk; drag on the right side to look around. RUN and CROUCH switch on and off (crouching is quieter and harder to spot). JUMP jumps. Logs and ladders can be climbed by walking into them.',
      es: 'Pon el pulgar izquierdo en cualquier punto de la mitad izquierda y arrastra para caminar; arrastra en la mitad derecha para mirar. CORRER y AGACHAR se activan y desactivan (agachado haces menos ruido y cuesta más verte). SALTAR salta. Los troncos y escaleras se trepan caminando hacia ellos.',
    },
    dig: {
      en: 'Hold ACTION to dig the block in the middle of the screen; harder blocks take longer. Tap or hold USE to place the selected block. Built-in fort walls and the cabin cannot be dug.',
      es: 'Mantén ACCIÓN para cavar el bloque del centro de la pantalla; los bloques duros tardan más. Toca o mantén USAR para colocar el bloque elegido. Los muros de los fuertes y la cabaña no se pueden cavar.',
    },
    hotbar: {
      en: 'Tap a slot in the hotbar to pick an item. BAG opens the inventory: tap an item, then a hotbar slot, to arrange the hotbar.',
      es: 'Toca una casilla de la barra rápida para elegir un objeto. BOLSA abre el inventario: toca un objeto y luego una casilla para ordenar la barra.',
    },
    water: {
      en: 'You can swim, but not for ever: watch the air bar under water. Craft a raft to cross lakes; place it on open water with USE and tap USE on it to board. Blocks placed from the water build a bridge.',
      es: 'Puedes nadar, pero no eternamente: vigila la barra de aire bajo el agua. Fabrica una balsa para cruzar lagos; colócala en agua abierta con USAR y toca USAR sobre ella para subir. Los bloques colocados desde el agua forman un puente.',
    },
    flashlight: {
      en: 'LIGHT turns the flashlight on and off. It lights tunnels and the night, but enemies can see you much farther away while it is on.',
      es: 'LUZ enciende y apaga la linterna. Ilumina túneles y la noche, pero el enemigo te ve desde mucho más lejos mientras está encendida.',
    },
    hunger: {
      en: 'Hunger slowly drops. Hunt animals, cook the meat on a campfire and eat it (select it and hold USE). Starving makes you sick and, in the end, kills you. Your own forts feed you while you are inside, and their ration crates give food (aim at one and tap USE).',
      es: 'El hambre baja poco a poco. Caza animales, cocina la carne en una hoguera y cómela (elígela y mantén USAR). Pasar hambre te enferma y al final te mata. Tus fuertes te alimentan mientras estás dentro y sus cajas de raciones dan comida (apunta a una y toca USAR).',
    },
    campfire: {
      en: 'Light a campfire with flint and steel (aim at the ground and tap USE). Next to a campfire, CRAFT opens campfire crafting: weapons, ammunition, TNT, grenades, rafts and more. Away from a fire, CRAFT opens simple crafting.',
      es: 'Enciende una hoguera con el pedernal y eslabón (apunta al suelo y toca USAR). Junto a una hoguera, FABRICAR abre la fabricación de la hoguera: armas, munición, TNT, granadas, balsas y más. Lejos del fuego, FABRICAR abre la fabricación sencilla.',
    },
    scope: {
      en: 'ZOOM (or USE with the sniper rifle) brings the scope up: a circular view with a fine reticle and a blurred dark surround, zooming smoothly. Without the sniper rifle, ZOOM uses binoculars. Your aim sways with your breathing. While zoomed, the buttons stay on top of the scope edge: ACTION fires and EXIT ZOOM lowers the scope. Ordinary guns keep the normal crosshair and the knife a dot.',
      es: 'ZOOM (o USAR con el fusil de francotirador) sube la mira: una vista circular con retícula fina y el borde oscuro y borroso, con zoom suave. Sin el fusil de francotirador, ZOOM usa los prismáticos. La puntería se mueve con la respiración. Con el zoom puesto los botones siguen visibles sobre el borde: ACCIÓN dispara y SALIR ZOOM baja la mira. Las demás armas usan la mira normal y el cuchillo un punto.',
    },
    grenades: {
      en: 'Tap ACTION to throw. Grenades explode after a short fuse; smoke grenades hide you from enemy eyes.',
      es: 'Toca ACCIÓN para lanzar. Las granadas explotan tras una mecha corta; las de humo te ocultan de los ojos enemigos.',
    },
    wheel: {
      en: 'While you have a squad, an ORDERS button appears: it opens a short list of orders (Follow me, Hold position, Defend the base, Spread out, Take cover, Attack this fort). Tap one to give it; it works at any time, also in the middle of a fight. Orders use what is in the middle of the screen when you open the list.',
      es: 'Mientras tengas escuadra aparece el botón ÓRDENES: abre una lista corta de órdenes (Seguidme, Mantened la posición, Defended la base, Dispersaos, A cubierto, Atacad este fuerte). Toca una para darla; funciona en cualquier momento, también en pleno combate. Las órdenes usan lo que hay en el centro de la pantalla al abrir la lista.',
    },
    recipients: {
      en: 'Orders from the ORDERS list go to your whole squad. To give an order to one soldier only, stand beside him and use the buttons that appear (FOLLOW ME, ASK FOR IRON, ASK FOR A WEAPON).',
      es: 'Las órdenes de la lista ÓRDENES van a toda la escuadra. Para hablar con un solo soldado, ponte a su lado y usa los botones que aparecen (SÍGUEME, PEDIR HIERRO, PEDIR UN ARMA).',
    },
    controls: {
      en: 'Left thumb (drag on the left side): move. Drag on the right side: look. ACTION: dig or attack (hold to keep digging or firing). USE: place, use, eat (hold), scope. JUMP: jump; in deep water double-tap JUMP to dive or swim on the surface, hold JUMP to swim up and DIVE to swim down. RUN and CROUCH switch on and off. ZOOM: binoculars or scope. LIGHT: flashlight. BAG: inventory. CRAFT: crafting. Tap a hotbar slot to pick an item. Tap the radar for the war map. II: pause. Squad buttons appear only when they make sense.',
      es: 'Pulgar izquierdo (arrastra en la mitad izquierda): moverse. Arrastra en la mitad derecha: mirar. ACCIÓN: cavar o atacar (mantén para seguir). USAR: colocar, usar, comer (mantén), mira. SALTAR: saltar; en agua profunda, doble toque de SALTAR para bucear o nadar en la superficie, mantén SALTAR para subir y BUCEAR para bajar. CORRER y AGACHAR se activan y desactivan. ZOOM: prismáticos o mira. LUZ: linterna. BOLSA: inventario. FABRICAR: fabricar. Toca una casilla de la barra para elegir objeto. Toca el radar para ver el mapa de guerra. II: pausa. Los botones de escuadra solo aparecen cuando tienen sentido.',
    },
    squadphone: {
      en: 'There are no permanent squad buttons. Stand beside an allied soldier and a FOLLOW ME button appears: it recruits him and the allies close to you, and also calls back soldiers who are holding or guarding. While you have a squad, a small ORDERS button opens a short list: Follow me, Hold position, Defend the base, Spread out, Take cover, Attack this fort. ASK FOR IRON and ASK FOR A WEAPON appear beside a soldier.',
      es: 'No hay botones de escuadra fijos. Ponte junto a un soldado aliado y aparece SÍGUEME: lo recluta a él y a los aliados cercanos, y también llama a los que mantienen posición o hacen guardia. Mientras tengas escuadra, un pequeño botón ÓRDENES abre una lista corta: Seguidme, Mantened la posición, Defended la base, Dispersaos, A cubierto, Atacad este fuerte. PEDIR HIERRO y PEDIR UN ARMA aparecen junto a un soldado.',
    },
    warmap: {
      en: 'Tap the radar in the top-left corner (or War map in the pause menu) to open the war map: every fort in its owner\'s colour (allied, enemy, unclaimed), your position, the cabin when playing alone and the current mission objective. Tap the map or Close to shut it.',
      es: 'Toca el radar de la esquina superior izquierda (o Mapa de guerra en el menú de pausa) para abrir el mapa de guerra: todos los fuertes con el color de su dueño (aliado, enemigo, sin dueño), tu posición, la cabaña si juegas solo y el objetivo de la misión. Toca el mapa o Cerrar para cerrarlo.',
    },
    music: {
      en: '"Marines\' Hymn", played by the United States Marine Band, plays quietly on the splash screen and the menus (after your first tap), loops smoothly and stops during play. Change its volume or mute it in Settings, or tap the speaker icon on the start screen. Your choice is remembered.',
      es: 'En la pantalla de presentación y en los menús suena en voz baja el "Marines\' Hymn" interpretado por la Banda de la Infantería de Marina de los Estados Unidos (tras tu primer toque); se repite sin cortes y se detiene al jugar. Cambia su volumen o siléncialo en Ajustes, o toca el icono del altavoz de la pantalla de inicio. Se recuerda tu elección.',
    },
    settings: {
      en: 'Language, graphics quality, render distance, sound volume, music volume and mute, look sensitivity and invert, blood on/off, minimap on/off and size and touch button size.',
      es: 'Idioma, calidad gráfica, distancia de dibujado, volumen del sonido, volumen y silencio de la música, sensibilidad e inversión de la vista, sangre sí/no, minimapa sí/no y tamaño y tamaño de los botones táctiles.',
    },
    m_hold: {
      en: 'Hold the Fort: a surprisingly large force tries to blow your door with TNT. Shoot the charges or walk up to them to pull the wires. You lose if the fort is taken.',
      es: 'Resistir en el fuerte: una fuerza sorprendentemente grande intenta volar tu puerta con TNT. Dispara a las cargas o acércate para arrancarles los cables. Pierdes si toman el fuerte.',
    },
  },
};
